baseurl = "https://olshansky.info/"
title = "🦉 olshansky 🦁"
theme = "PaperMod"
languagecode = "en"
defaultcontentlanguage = "en"

# Suppress raw HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']

# Disable pagination - show all items on one page
[pagination]
  pagerSize = 1000

# Commenting out Disqus for now
# disqusShortname = "olshansky"

# https://analytics.google.com/analytics/web
googleAnalytics = 'G-15DW3DE66X'

[markup.highlight]
style = "monokai"

[params]
  author = "Daniel Olshansky"
  description = "Everything about Olshansky"
  keywords = ["blog", "developer", "personal"]

  # Show reading time and word count
  ShowReadingTime = true
  ShowWordCount = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  ShowToc = true
  TocOpen = false
  hideSummary = false
  hideFooter = false
  ShowFullTextinRSS = false

  # Enable search
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

  # Home page configuration
  mainSections = ["posts"]

  # Color scheme
  defaultTheme = "dark"
  disableThemeToggle = false

  # Custom date format
  DateFormat = "January 2, 2006"

  # Favicon
  favicon = "/img/favicon-32x32.png"
  favicon16x16 = "/img/favicon-16x16.png"
  favicon32x32 = "/img/favicon-32x32.png"

  # Profile mode configuration for home page
  [params.profileMode]
    enabled = true
    title = "Daniel Olshansky"
    subtitle = "Figuring out what I want to do instead of what I want to want to do"
    imageUrl = "/images/charicature.jpeg"
    imageWidth = 200
    imageHeight = 200
    imageTitle = "Daniel Olshansky"

    [[params.profileMode.buttons]]
      name = "Posts"
      url = "posts"
    [[params.profileMode.buttons]]
      name = "Books"
      url = "book"
    [[params.profileMode.buttons]]
      name = "Movies"
      url = "movie"
    [[params.profileMode.buttons]]
      name = "Shows"
      url = "tv"

  # Social Icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/olshansk"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/olshansky"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/dolshansky"

  [[params.socialIcons]]
    name = "rss"
    url = "https://olshansky.info/index.xml"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Search page
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Menu configuration
[[menu.main]]
  name = "About"
  weight = 1
  url = "/about/"

[[menu.main]]
  name = "Posts"
  weight = 2
  url = "/posts/"

[[menu.main]]
  name = "Thoughts"
  weight = 3
  url = "/thoughts/"

[[menu.main]]
  name = "Books"
  weight = 4
  url = "/book/"

[[menu.main]]
  name = "Movies"
  weight = 5
  url = "/movie/"

[[menu.main]]
  name = "Shows"
  weight = 6
  url = "/tv/"

[[menu.main]]
  name = "Search"
  weight = 7
  url = "/search/"

# CSP Configuration (if needed later)
[params.csp]
  childsrc = ["'self'"]
  fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
  formaction = ["'self'"]
  framesrc = ["'self'", "https://www.youtube.com"]
  imgsrc = ["'self'"]
  objectsrc = ["'none'"]
  stylesrc = [
    "'self'",
    "'unsafe-inline'",
    "https://fonts.googleapis.com/",
    "https://cdn.jsdelivr.net/",
  ]
  scriptsrc = [
    "'self'",
    "'unsafe-inline'",
    "https://www.google-analytics.com",
    "https://cdn.jsdelivr.net/",
    "https://assets.onedollarstats.com",
  ]
  prefetchsrc = ["'self'"]
  connectsrc = [
    "'self'",
    "https://www.google-analytics.com",
    "https://api.onedollarstats.com",
  ]

[params.onedollarstats]
    id = "olshansky.info"

[params.social]
  twitter = "olshansky"