# Reference: https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md

baseurl = "http://www.olshansky.info"
title = "olshansky"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Daniel Olshansky"
  info = "Full Stack DevOps and Magician"
  description = "Olshansky's Personal Site"
  keywords = "blog,developer,personal"
  avatarurl = "images/charicature.jpeg"
  gravatar = "olshansky.daniel@gmail.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 1992

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/olshansky/"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/olshansky/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/dolshansky/"


[[params.social]]
  name = "Substack"
  icon = "fa fa-substack fa-2x"
  weight = 2
  url = "https://olshansky.substack.com"

[[params.social]]
  name = "Medium"
  icon = "fa fa-medium fa-2x"
  weight = 2
  url = "https://olshansky.medium.com"

# Menu links

[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "Books"
  weight = 2
  url = "books/"

[[menu.main]]
  name = "Movies"
  weight = 2
  url = "movies/"