baseurl = "http://www.olshansky.info"
title = "olshansky"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "olshansky"

[markup.highlight]
style = "github-dark"

[params]
  author = "Daniel Olshansky"
  info = "Figuring out what I want to do instead of what I want want to want to do"
  description = "Everything about Olshansky"
  keywords = "blog,developer,personal"
  avatarURL = "/images/charicature.jpeg"
  # gravatar = "olshansky.daniel@gmail.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 1992

  maxSeeAlsoItems = 5
  commit = false
  rtl = false
  math = false
  katex = false

  colorScheme = "dark"
  hideColorSchemeToggle = false

  # customCSS = ["css/all.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

  enableTwemoji = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/olshansk"

[[params.social]]
  name = "Substack"
  icon = "fa fa-pencil fa-2x"
  weight = 1
  url = "https://olshansky.substack.com"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 1
  url = "https://twitter.com/olshansky"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/dolshansky"

[[params.social]]
  name = "Medium"
  icon = "fa fa-medium fa-2x"
  weight = 1
  url = "https://olshansky.medium.com"

[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 1
  url = "https://instagram.com/olshansk"

# Menu links

# [[menu.main]]
#   name = "About"
#   weight = 1
#   url = "about/"

# [[menu.main]]
#   name = "Contact"
#   weight = 1
#   url = "contact/"

# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url  = "posts/"

[[menu.main]]
  name = "Books"
  weight = 1
  # url = "books/"
  url = "https://www.goodreads.com/user/show/19157738-daniel-olshansky"

[[menu.main]]
  name = "Movies & TV"
  weight = 1
  # url = "movies/"
  url = "https://www.rottentomatoes.com/profiles/GeDt0zCK1fenF8NTwehrduK0seeCXJTL4H28fjquRRCzRi1zIknSwBFllCxgFepIjgSZRuYYCdOcNGtk2Fv2HmWu9zSxLTZQfJjIB1FVKuYj"

[[menu.main]]
  name = "Videos"
  weight = 1
  # url = "movies/"
  url = "https://www.youtube.com/playlist?list=PLeHvNSh0enXSflgNf-YC6jW6K3Fh4cS5E"

[[menu.main]]
  name = "Publications"
  weight = 1
  # url = "movies/"
  url = "https://scholar.google.com.tr/citations?user=pkPj80UAAAAJ&hl=fil"